// Kamus Arab: Judul bab KB (dipakai di Rujukan dan Latihan). Kunci = teks Indonesia persis seperti di kode; nilai = teks Arab.
// Draf terjemahan, perlu dicek tim keilmuan. Untuk kata lepas di dalam kalimat (soal, materi) lihat istilah.ts.

export const KAMUS_BAB: Record<string, string> = {
  'Hajb': 'الحجب',
  'Ashabul Furudh': 'أصحاب الفروض',
  'Asas Kewarisan': 'أسس الميراث',
  'Daftar dan Klasifikasi Ahli Waris': 'قائمة الورثة وتصنيفهم',
  'Indeks dan Konvensi Knowledge Base': 'فهرس قاعدة المعرفة واصطلاحاتها',
  'Pendahuluan dan Hak-hak atas Tirkah': 'مقدمة والحقوق المتعلقة بالتركة',
  'Kakek Bersama Saudara': 'الجد مع الإخوة',
  'Hisab': 'الحساب',
  'Munasakhat': 'المناسخات',
  'Masalah Khusus Furudh': 'مسائل خاصة في الفروض',
  'Pembagian Tirkah (Qismah) dan Takharuj': 'قسمة التركة والتخارج',
  'Pembagian Tirkah': 'قسمة التركة والتخارج',
  'Kasus Khusus': 'المسائل الخاصة',
  'Kasus Uji (Test Cases) Terverifikasi': 'مسائل الاختبار الموثقة',
  'Kasus Uji': 'مسائل الاختبار',
  'Glosarium Istilah Faraidh': 'مسرد مصطلحات الفرائض',
  'Daftar Rujukan dan Metodologi Pengutipan': 'قائمة المراجع ومنهج الاستشهاد',
  'Dzawil Arham': 'ذوو الأرحام',
  "Asas Kewarisan (Syarat, Rukun, Asbab, Mawani')": 'أسس الميراث (الشروط والأركان والأسباب والموانع)',
  'Ashabul Furudh (Furudh Muqaddarah dan 11 Ahli Waris)': 'أصحاب الفروض (الفروض المقدرة وأصحابها الأحد عشر)',
  'Hajb (Penghalangan)': 'الحجب',
  "Masalah Khusus Furudh ('Umariyyatain dan Musyarrakah)": 'مسائل خاصة في الفروض (العمريتان والمشرّكة)',
  'Kakek Bersama Saudara (al-Jadd wal-Ikhwah)': 'الجد والإخوة',
  "Hisab (Ashlul Mas'alah, 'Aul, Radd)": 'الحساب (أصل المسألة والعول والرد)',
  'Tashih (Koreksi Pembagian)': 'تصحيح المسائل',
  'Munasakhat (Kematian Berantai)': 'المناسخات',
  "Kasus Khusus (Haml, Mafqud, Khuntsa, Gharqa, Murtad, Anak Li'an/Zina, Laqith)": 'حالات خاصة (الحمل والمفقود والخنثى والغرقى والمرتد وولد اللعان والزنا واللقيط)',
};
