// Kamus Arab: Halaman Belajar dan materi pelajaran (judul modul/pelajaran juga di sini). Kunci = teks Indonesia persis seperti di kode; nilai = teks Arab.
// Draf terjemahan, perlu dicek tim keilmuan. Untuk kata lepas di dalam kalimat (soal, materi) lihat istilah.ts.

export const KAMUS_BELAJAR: Record<string, string> = {
  'Pusat belajar faraidh': 'مركز تعلم الفرائض',
  'Mulai dari sini': 'ابدأ من هنا',
  'Lanjutkan': 'تابع',
  'Modul {nomor}': 'الوحدة {nomor}',
  'Semua pelajaran sudah selesai. Mantap!': 'أتممت جميع الدروس. أحسنت!',
  'Materi berurutan, dari pengantar sampai menghitung.': 'دروس متسلسلة من المقدمة إلى الحساب.',
  'Uji pemahaman setelah membaca materi.': 'اختبر فهمك بعد قراءة الدروس.',
  'Soal hitung dikerjakan': 'مسائل حسابية محلولة',
  'Kuis konsep dijawab benar': 'أسئلة مفاهيم أجيب عنها صوابا',
  'Soal campuran semua bab': 'أسئلة منوعة من كل الأبواب',
  'Buka kapan saja saat ada istilah atau hukum yang belum jelas.': 'ارجع إليه متى أشكل عليك مصطلح أو حكم.',
  'Cheatsheet': 'ملخصات',
  'Ringkasan satu halaman untuk dicetak atau disimpan.': 'ملخص في صفحة واحدة للطباعة أو الحفظ.',
  'Terakhir kamu buka': 'آخر ما فتحته',
  'Reset progres belajar': 'إعادة تعيين تقدم التعلم',
  'Hukum': 'الحكم',
  'Arti': 'المعنى',
  'Tafsir': 'التفسير',
  'skor': 'النتيجة',
  'Pelajaran': 'الدروس',
  'Kuis': 'الاختبارات',
  'Hapus {judul} dari riwayat': 'حذف {judul} من السجل',
  'Hapus dari riwayat': 'حذف من السجل',
  'Hapus semua riwayat belajar': 'حذف كل سجل التعلم',
  'Pelajaran selesai, soal hitung, skor kuis, dan riwayat belajar dikosongkan. Riwayat hitung tidak ikut terhapus.': 'تصفّر الدروس المنتهية والمسائل الحسابية ونتائج الاختبارات وسجل التعلم. أما سجل الحساب فلا يحذف.',
  'Reset progres': 'إعادة التعيين',
  '{pelajaran} pelajaran selesai, {soal} soal hitung, dan semua skor kuis akan kembali ke nol. Ini tidak bisa dibatalkan.': '{pelajaran} درسا منتهيا و{soal} مسألة حسابية وجميع نتائج الاختبارات ستعود إلى الصفر. لا يمكن التراجع عن هذا.',
  'Daftar "Terakhir kamu buka" akan dikosongkan. Progres pelajaran dan skor tetap tersimpan.': 'ستفرغ قائمة «آخر ما فتحته». يبقى تقدم الدروس والنتائج محفوظا.',
  '"{judul}" dihapus dari daftar. Progres dan skornya tetap tersimpan.': 'سيحذف «{judul}» من القائمة. يبقى تقدمه ونتيجته محفوظين.',
  'Progres {persen}%, {label}': 'التقدم {persen}%، {label}',
  'Reset semua progres belajar?': 'إعادة تعيين كل تقدم التعلم؟',
  'Hapus semua riwayat belajar?': 'حذف كل سجل التعلم؟',
  'Hapus dari riwayat belajar?': 'الحذف من سجل التعلم؟',
  'Pelajaran ini tidak ditemukan.': 'لم يوجد هذا الدرس.',
  'Modul {nomor} · {judul} · Pelajaran {indeks} dari {total}': 'الوحدة {nomor} · {judul} · الدرس {indeks} من {total}',
  'Navigasi pelajaran': 'التنقل بين الدروس',
  'Sebelumnya': 'السابق',
  'Berikutnya': 'التالي',
  'Beranda belajar': 'الصفحة الرئيسية للتعلم',
  'Daftar materi': 'قائمة الدروس',
  'Progres belajar': 'تقدم التعلم',
  'menyusul': 'قريبا',
  'selesai': 'منتهٍ',
  'Contoh ini tidak bisa dihitung. Laporkan ke pengembang.': 'تعذر حساب هذا المثال. أبلغ المطورين.',
  'Dihitung otomatis': 'محسوب تلقائيا',
  'Buka di Hitung': 'افتح في الحساب',
};
