// Kamus Arab: Halaman Belajar dan materi pelajaran (judul modul/pelajaran juga di sini). Kunci = teks Indonesia persis seperti di kode; nilai = teks Arab.
// Draf terjemahan, perlu dicek tim keilmuan. Untuk kata lepas di dalam kalimat (soal, materi) lihat istilah.ts.

export const KAMUS_BELAJAR: Record<string, string> = {
  'Pusat belajar faraidh': 'مركز تعلم الفرائض',
  'Mulai dari sini': 'ابدأ من هنا',
  'Lanjutkan': 'تابع',
  'Modul {nomor}': 'الوحدة {nomor}',
  'Semua pelajaran sudah selesai. Mantap!': 'أتممت جميع الدروس. أحسنت!',
  'Materi berurutan, dari pengantar sampai menghitung.': 'دروس متسلسلة من المقدمة إلى الحساب.',
  'Uji pemahaman setelah membaca materi.': 'اختبر فهمك بعد قراءة الدروس.',
  'Soal hitung dikerjakan': 'مسائل حسابية محلولة',
  'Kuis konsep dijawab benar': 'أسئلة مفاهيم أجيب عنها صوابا',
  'Soal campuran semua bab': 'أسئلة منوعة من كل الأبواب',
  'Buka kapan saja saat ada istilah atau hukum yang belum jelas.': 'ارجع إليه متى أشكل عليك مصطلح أو حكم.',
  'Cheatsheet': 'ملخصات',
  'Ringkasan satu halaman untuk dicetak atau disimpan.': 'ملخص في صفحة واحدة للطباعة أو الحفظ.',
  'Terakhir kamu buka': 'آخر ما فتحته',
  'Reset progres belajar': 'إعادة تعيين تقدم التعلم',
  'Hukum': 'الحكم',
  'Arti': 'المعنى',
  'Tafsir': 'التفسير',
  'skor': 'النتيجة',
  'Pelajaran': 'الدروس',
  'Kuis': 'الاختبارات',
  'Hapus {judul} dari riwayat': 'حذف {judul} من السجل',
  'Hapus dari riwayat': 'حذف من السجل',
  'Hapus semua riwayat belajar': 'حذف كل سجل التعلم',
  'Pelajaran selesai, soal hitung, skor kuis, dan riwayat belajar dikosongkan. Riwayat hitung tidak ikut terhapus.': 'تصفّر الدروس المنتهية والمسائل الحسابية ونتائج الاختبارات وسجل التعلم. أما سجل الحساب فلا يحذف.',
  'Reset progres': 'إعادة التعيين',
  '{pelajaran} pelajaran selesai, {soal} soal hitung, dan semua skor kuis akan kembali ke nol. Ini tidak bisa dibatalkan.': '{pelajaran} درسا منتهيا و{soal} مسألة حسابية وجميع نتائج الاختبارات ستعود إلى الصفر. لا يمكن التراجع عن هذا.',
  'Daftar "Terakhir kamu buka" akan dikosongkan. Progres pelajaran dan skor tetap tersimpan.': 'ستفرغ قائمة «آخر ما فتحته». يبقى تقدم الدروس والنتائج محفوظا.',
  '"{judul}" dihapus dari daftar. Progres dan skornya tetap tersimpan.': 'سيحذف «{judul}» من القائمة. يبقى تقدمه ونتيجته محفوظين.',
  'Progres {persen}%, {label}': 'التقدم {persen}%، {label}',
  'Reset semua progres belajar?': 'إعادة تعيين كل تقدم التعلم؟',
  'Hapus semua riwayat belajar?': 'حذف كل سجل التعلم؟',
  'Hapus dari riwayat belajar?': 'الحذف من سجل التعلم؟',
  'Pelajaran ini tidak ditemukan.': 'لم يوجد هذا الدرس.',
  'Modul {nomor} · {judul} · Pelajaran {indeks} dari {total}': 'الوحدة {nomor} · {judul} · الدرس {indeks} من {total}',
  'Navigasi pelajaran': 'التنقل بين الدروس',
  'Sebelumnya': 'السابق',
  'Berikutnya': 'التالي',
  'Beranda belajar': 'الصفحة الرئيسية للتعلم',
  'Daftar materi': 'قائمة الدروس',
  'Progres belajar': 'تقدم التعلم',
  'menyusul': 'قريبا',
  'selesai': 'منتهٍ',
  'Contoh ini tidak bisa dihitung. Laporkan ke pengembang.': 'تعذر حساب هذا المثال. أبلغ المطورين.',
  'Dihitung otomatis': 'محسوب تلقائيا',
  'Buka di Hitung': 'افتح في الحساب',
  'Pengantar': 'مقدمة',
  'Siapa ahli waris': 'من هم الورثة',
  'Bagian pasti (furudh)': 'الأنصبة المقدرة (الفروض)',
  'Penghalang (hajb)': 'الحجب',
  'Kakek & saudara': 'الجد والإخوة',
  'Menghitung': 'الحساب',
  'Pembagian nominal': 'القسمة بالمبالغ',
  'Apa itu faraidh dan apa yang dibereskan sebelum harta dibagi': 'ما الفرائض وما الذي يقدم قبل قسمة المال',
  'Rukun, syarat, sebab, penghalang, dan daftar ahli waris': 'الأركان والشروط والأسباب والموانع وقائمة الورثة',
  "Enam bagian dalam Al-Qur'an dan siapa pemiliknya": 'الفروض الستة في القرآن ومن يستحقها',
  'Yang mengambil sisa, jenis-jenisnya, dan urutannya': 'من يأخذ الباقي وأنواعه وترتيبه',
  'Ahli waris yang terhalang atau berkurang bagiannya': 'الوارث المحجوب أو الذي ينقص نصيبه',
  'Muqasamah dan akdariyyah': 'المقاسمة والأكدرية',
  "Ashlul mas'alah, 'aul, dan radd": 'أصل المسألة والعول والرد',
  'Supaya bagian tiap orang jadi bilangan bulat': 'ليصير نصيب كل واحد عددا صحيحا',
  'Dari saham ke rupiah': 'من السهام إلى الروبية',
  'Ahli waris wafat sebelum harta dibagi': 'موت الوارث قبل قسمة التركة',
  'Apa itu faraidh?': 'ما الفرائض؟',
  'Mengenal arti faraidh, dalil pokoknya, dan kenapa ilmu ini dipelajari.': 'التعرف على معنى الفرائض وأدلتها الأصلية وسبب تعلم هذا العلم.',
  'Harta dibereskan dulu, baru dibagi': 'تسوية التركة أولا ثم قسمتها',
  'Memahami urutan hak yang diambil dari tirkah sebelum sisanya dibagi ke ahli waris.': 'فهم ترتيب الحقوق التي تؤخذ من التركة قبل قسمة الباقي على الورثة.',
  'Rukun, syarat, dan sebab mewarisi': 'أركان الإرث وشروطه وأسبابه',
  'Tahu kapan warisan terjadi dan hubungan apa yang membuat seseorang mewarisi.': 'معرفة متى يقع الإرث وأي علاقة تجعل الشخص وارثا.',
  "Penghalang mewarisi (mawani')": 'موانع الإرث',
  'Mengenal lima hal yang membuat kerabat tidak mewarisi sama sekali.': 'التعرف على خمسة أمور تمنع القريب من الميراث تماما.',
  'Siapa saja ahli waris?': 'من هم الورثة؟',
  'Menghafal 15 ahli waris laki-laki dan 10 perempuan, serta tahu siapa yang bukan ahli waris.': 'حفظ الورثة الخمسة عشر من الرجال والعشرة من النساء، ومعرفة من ليس بوارث.',
  'Enam bagian pasti, dan bagian suami-istri': 'الفروض الستة ونصيب الزوجين',
  "Mengenal enam fardh dalam Al-Qur'an dan menghitung bagian suami atau istri.": 'التعرف على الفروض الستة في القرآن وحساب نصيب الزوج أو الزوجة.',
  'Ayah, ibu, kakek, dan nenek': 'الأب والأم والجد والجدة',
  'Menentukan bagian orang tua dan kakek-nenek dalam tiap keadaan.': 'تحديد نصيب الوالدين والجد والجدة في كل حال.',
  'Anak perempuan, cucu perempuan, dan saudari': 'البنت وبنت الابن والأخت',
  'Menentukan bagian anak dan cucu perempuan, saudari kandung/sebapak, dan saudara seibu.': 'تحديد نصيب البنت وبنت الابن والأخت الشقيقة أو لأب والأخ لأم.',
  'Tiga jenis ashabah': 'أنواع العصبة الثلاثة',
  "Membedakan ashabah bi nafsihi, bil ghair, dan ma'al ghair.": 'التمييز بين العصبة بالنفس وبالغير ومع الغير.',
  'Siapa yang didahulukan mengambil sisa?': 'من يقدم في أخذ الباقي؟',
  'Mengurutkan ashabah dengan kaidah arah, kedekatan, dan kekuatan.': 'ترتيب العصبة بقواعد الجهة والقرب والقوة.',
  'Hajb, ketika ahli waris terhalang': 'الحجب حين يحجب الوارث',
  'Membedakan hajb hirman dan hajb nuqshan, serta tahu siapa menghalangi siapa.': 'التمييز بين حجب الحرمان وحجب النقصان ومعرفة من يحجب من.',
};
