// Kamus Arab: Halaman Latihan: soal hitung dan kuis konsep. Kunci = teks Indonesia persis seperti di kode; nilai = teks Arab.
// Draf terjemahan, perlu dicek tim keilmuan. Untuk kata lepas di dalam kalimat (soal, materi) lihat istilah.ts.

export const KAMUS_LATIHAN: Record<string, string> = {
  'Kerjakan soal hitung dari kasus nyata, atau uji pemahaman konsep lewat kuis per bab.': 'حل مسائل حسابية من وقائع حقيقية، أو اختبر فهمك للمفاهيم باختبارات لكل باب.',
  'Jenis latihan': 'نوع التمرين',
  'Kuis konsep': 'اختبار المفاهيم',
  '{jumlah} menit': '{jumlah} دقيقة',
  '{jumlah} detik': '{jumlah} ثانية',
  '{jumlah} soal dari semua bab': '{jumlah} أسئلة من كل الأبواب',
  'Skor terakhir': 'آخر نتيجة',
  '{jumlah} soal': '{jumlah} أسئلة',
  'Keluar dari kuis?': 'الخروج من الاختبار؟',
  'Jawabanmu di sesi ini ({terjawab} dari {total} soal) tidak disimpan.': 'إجاباتك في هذه الجلسة ({terjawab} من {total} أسئلة) لن تحفظ.',
  'Lanjut mengerjakan': 'واصل الحل',
  'Keluar': 'خروج',
  'Kuis ini tidak ada.': 'هذا الاختبار غير موجود.',
  'Kembali ke daftar kuis': 'العودة إلى قائمة الاختبارات',
  'Pilih mode': 'اختر النمط',
  'Mode latihan': 'نمط التمرين',
  'Jawaban yang tepat dan pembahasannya muncul setiap selesai menjawab.': 'تظهر الإجابة الصحيحة وشرحها بعد كل إجابة.',
  'Mode ujian': 'نمط الامتحان',
  'Waktunya {durasi}. Jawaban yang tepat baru muncul setelah selesai atau waktu habis.': 'مدته {durasi}. لا تظهر الإجابات الصحيحة إلا بعد الانتهاء أو انتهاء الوقت.',
  'Mulai kuis': 'ابدأ الاختبار',
  'Benar {jumlah}': 'الصحيح {jumlah}',
  'Sisa waktu {durasi}': 'الوقت المتبقي {durasi}',
  'Soal {nomor}': 'السؤال {nomor}',
  'Soal sebelumnya': 'السؤال السابق',
  'Soal berikutnya': 'السؤال التالي',
  'Selesaikan': 'أنهِ',
  'Navigasi soal': 'التنقل بين الأسئلة',
  'Soal {nomor}, {status}': 'السؤال {nomor}، {status}',
  'terjawab': 'تمت الإجابة',
  'belum dijawab': 'لم يجب',
  'Terjawab': 'تمت الإجابة',
  'Belum': 'لم يجب',
  'Skor': 'النتيجة',
  'Benar': 'صحيح',
  'Salah': 'خطأ',
  'Nilai': 'الدرجة',
  'Pilih kuis lain': 'اختر اختبارا آخر',
  'Kerjakan lagi': 'أعد الحل',
  'Soal {nomor}.': 'السؤال {nomor}.',
  'Tidak dijawab (waktu habis)': 'لم يجب (انتهى الوقت)',
  'Jawaban tepat': 'الإجابة الصحيحة',
  'Belum tepat, jawabannya {huruf}': 'غير صحيح، الإجابة {huruf}',
  'Coba lagi': 'حاول مجددا',
  'Progres soal hitung': 'تقدم المسائل الحسابية',
  'soal dikerjakan': 'مسألة محلولة',
  'sudah dikerjakan': 'تم حلها',
  'belum dikerjakan': 'لم تحل بعد',
  'Ulangi': 'أعد',
};
