// Kamus Arab: Halaman Rujukan, chip dan lembar Dalil. Kunci = teks Indonesia persis seperti di kode; nilai = teks Arab.
// Draf terjemahan, perlu dicek tim keilmuan. Untuk kata lepas di dalam kalimat (soal, materi) lihat istilah.ts.

export const KAMUS_RUJUKAN: Record<string, string> = {
  "Al-Qur'an, sunnah, atsar, ijma', dan kitab madzhab yang menjadi dasar tiap hukum di aplikasi ini.": 'القرآن والسنة والآثار والإجماع وكتب المذهب التي بنيت عليها أحكام هذا التطبيق.',
  'Kategori dalil': 'أنواع الأدلة',
  'Dalil terpilih': 'الدليل المختار',
  "Al-Qur'an": 'القرآن الكريم',
  'Sunnah': 'السنة',
  'Atsar sahabat': 'آثار الصحابة',
  "Ijma'": 'الإجماع',
  'Kitab madzhab': 'كتب المذهب',
  'Kaidah hisab': 'قواعد الحساب',
  'Keterangan': 'فوائد',
  'Masih dikaji': 'قيد الدراسة',
  'Dalil': 'الدليل',
  'Buka di Rujukan': 'افتح في المراجع',
  'Lihat di halaman Rujukan': 'انظر في صفحة المراجع',
  'Nomor hadits bisa berbeda antar cetakan; cocokkan dengan lafaznya.': 'قد يختلف رقم الحديث بين الطبعات؛ فطابقه باللفظ.',
  'Perlu dicek': 'يحتاج تحققا',
  'Keterangan {surah} {ayat}': 'بيان {surah} {ayat}',
  'Belum ada rincian hukum untuk ayat ini.': 'لا توجد أحكام مفصلة لهذه الآية بعد.',
  'Baca di sini': 'اقرأ هنا',
  'Baca di sini · belum tersedia': 'اقرأ هنا · غير متاح بعد',
  'Situs sumber': 'موقع المصدر',
  'Situs sumber · belum tersedia': 'موقع المصدر · غير متاح بعد',
  'Kembali ke daftar kitab': 'العودة إلى قائمة الكتب',
  'Berkas kitab ini belum tersedia.': 'ملف هذا الكتاب غير متاح بعد.',
  'Dipakai untuk': 'يستعمل في',
  '(masih dikaji)': '(قيد الدراسة)',
  'Kembali ke rujukan': 'العودة إلى المراجع',
  'Rujukan {kode} tidak ada di daftar.': 'المرجع {kode} غير موجود في القائمة.',
  'Arti ayat ini belum diisi. Akan ditambahkan tim keilmuan.': 'معنى هذه الآية لم يكتب بعد. سيضيفه الفريق العلمي.',
  'Tafsir ayat ini belum diisi. Akan ditambahkan tim keilmuan.': 'تفسير هذه الآية لم يكتب بعد. سيضيفه الفريق العلمي.',
  "An-Nisa'": 'النساء',
  'An-Nisa': 'النساء',
  'Al-Anfal': 'الأنفال',
  'Al-Ahzab': 'الأحزاب',
  'Al-Baqarah': 'البقرة',
};
