// Kamus Arab: Umum (dipakai lebih dari satu halaman): navigasi, tombol bersama. Kunci = teks Indonesia persis seperti di kode; nilai = teks Arab.
// Draf terjemahan, perlu dicek tim keilmuan. Untuk kata lepas di dalam kalimat (soal, materi) lihat istilah.ts.

export const KAMUS_UMUM: Record<string, string> = {
  'Beranda': 'الرئيسية',
  'Belajar': 'التعلم',
  'Latihan': 'التمارين',
  'Rujukan': 'المراجع',
  'Menu utama': 'القائمة الرئيسية',
  'Bahasa': 'اللغة',
  'Tur singkat': 'جولة قصيرة',
  'Reset skenario': 'إعادة المسألة',
  'Reset skenario?': 'إعادة المسألة؟',
  'Reset': 'إعادة',
  'Arif Waris, beranda': 'عارف وارث، الرئيسية',
  'by Prodi HKI STDI Imam Syafi\'i': 'قسم الأحوال الشخصية، المعهد العالي للدراسات الإسلامية الإمام الشافعي',
  'Batal': 'إلغاء',
  'Tutup': 'إغلاق',
  'Simpan': 'حفظ',
  'Hapus': 'حذف',
  'Hapus semua': 'حذف الكل',
  'Kembali': 'رجوع',
  '← Kembali': 'رجوع →',
  'Lanjut →': '← التالي',
  'Berikutnya →': '← التالي',
  '← Sebelumnya': 'السابق →',
  'Selesai': 'تم',
  'Selesai!': 'تم!',
  'Kelar': 'تم',
  'Oke, paham': 'حسنا، فهمت',
  'Ada': 'نعم',
  'Tidak ada': 'لا يوجد',
  'Belum ada': 'لا يوجد بعد',
  'Belum diisi': 'لم يعبأ بعد',
  'Belum dipilih': 'لم يختر بعد',
  'Contoh': 'مثال',
  'Catatan.': 'تنبيه.',
  'Kenapa?': 'لماذا؟',
  'Kenapa begitu?': 'ما الدليل؟',
  'Dalilnya': 'الدليل',
  'Segera hadir': 'قريبا',
  'Terkunci': 'مقفل',
  'Tujuan': 'الهدف',
  'Nama': 'الاسم',
  'Jumlah': 'العدد',
  'Ketik': 'اكتب',
  'Jawab': 'أجب',
  'Pindah': 'انتقل',
  'Tetap di sini': 'البقاء هنا',
  'Tinggalkan ArifLab?': 'مغادرة ArifLab؟',
  'Kasusmu tersimpan di Riwayat hitung. Buka menu ArifLab kapan saja untuk melanjutkan.': 'مسألتك محفوظة في سجل الحساب. افتح ArifLab متى شئت لتكملها.',
  'Soal ini bisa kamu buka lagi kapan saja dari Latihan.': 'يمكنك فتح هذا التمرين مرة أخرى من صفحة التمارين.',
  'Nemu masalah? Laporkan': 'وجدت خطأ؟ أبلغنا',
  'Laporkan ke pengembang': 'أبلغ المطورين',
  'FAQ': 'أسئلة شائعة',
  'FAQ faraidh': 'أسئلة شائعة في الفرائض',
  'Glosarium': 'المصطلحات',
  'Glosarium faraidh': 'مصطلحات الفرائض',
  'Rujukan faraidh': 'مراجع الفرائض',
  'Tanya jawab': 'سؤال وجواب',
  'Tanya jawab kasus waris': 'سؤال وجواب في مسائل الميراث',
  'Bantuan cepat': 'مساعدة سريعة',
  'Draf, menunggu pengecekan tim keilmuan.': 'مسودة، في انتظار مراجعة الفريق العلمي.',
  'Tautan disalin': 'تم نسخ الرابط',
  'Gagal menyalin. Salin dari bilah alamat.': 'تعذر النسخ. انسخ من شريط العنوان.',
  ' dan ': ' و',
  'Kuis acak': 'اختبار عشوائي',
  'Soal hitung': 'مسائل حسابية',
  'Draf, belum direview tim keilmuan': 'مسودة لم يراجعها الفريق العلمي بعد',
  'Soal {nomor} dari {total}': 'السؤال {nomor} من {total}',
};
