// Kamus UI Indonesia → Arab (bahasa 'ar'). Kunci = teks Indonesia persis seperti di kode (termasuk spasi tepi).
// Draf terjemahan, perlu dicek tim keilmuan. Yang belum ada di sini tampil dalam bahasa Indonesia.
// Nama orang, merek (ARIF, ArifLab) dan "Rp" sengaja tidak diterjemahkan.

export const PERLU_CEK_KAMUS = true;

export const KAMUS_ARAB: Record<string, string> = {
  // ─── Navigasi & umum ───
  'Beranda': 'الرئيسية',
  'Belajar': 'التعلم',
  'Latihan': 'التمارين',
  'Rujukan': 'المراجع',
  'Menu utama': 'القائمة الرئيسية',
  'Bahasa': 'اللغة',
  'Tur singkat': 'جولة قصيرة',
  'Reset skenario': 'إعادة المسألة',
  'Reset skenario?': 'إعادة المسألة؟',
  'Reset': 'إعادة',
  'Arif Waris, beranda': 'عارف وارث، الرئيسية',
  'by Prodi HKI STDI Imam Syafi\'i': 'قسم الأحوال الشخصية، المعهد العالي للدراسات الإسلامية الإمام الشافعي',
  'Batal': 'إلغاء',
  'Tutup': 'إغلاق',
  'Simpan': 'حفظ',
  'Hapus': 'حذف',
  'Hapus semua': 'حذف الكل',
  'Kembali': 'رجوع',
  '← Kembali': 'رجوع →',
  'Lanjut →': '← التالي',
  'Berikutnya →': '← التالي',
  '← Sebelumnya': 'السابق →',
  'Selesai': 'تم',
  'Selesai!': 'تم!',
  'Kelar': 'تم',
  'Oke, paham': 'حسنا، فهمت',
  'Ada': 'نعم',
  'Tidak ada': 'لا يوجد',
  'Belum ada': 'لا يوجد بعد',
  'Belum diisi': 'لم يعبأ بعد',
  'Belum dipilih': 'لم يختر بعد',
  'Contoh': 'مثال',
  'Catatan.': 'تنبيه.',
  'Kenapa?': 'لماذا؟',
  'Kenapa begitu?': 'ما الدليل؟',
  'Dalilnya': 'الدليل',
  'Segera hadir': 'قريبا',
  'Terkunci': 'مقفل',
  'Tujuan': 'الهدف',
  'Nama': 'الاسم',
  'Jumlah': 'العدد',
  'Ketik': 'اكتب',
  'Jawab': 'أجب',
  'Pindah': 'انتقل',
  'Tetap di sini': 'البقاء هنا',
  'Tinggalkan ArifLab?': 'مغادرة ArifLab؟',
  'Kasusmu tersimpan di Riwayat hitung. Buka menu ArifLab kapan saja untuk melanjutkan.': 'مسألتك محفوظة في سجل الحساب. افتح ArifLab متى شئت لتكملها.',
  'Soal ini bisa kamu buka lagi kapan saja dari Latihan.': 'يمكنك فتح هذا التمرين مرة أخرى من صفحة التمارين.',
  'Nemu masalah? Laporkan': 'وجدت خطأ؟ أبلغنا',
  'Laporkan ke pengembang': 'أبلغ المطورين',
  'FAQ': 'أسئلة شائعة',
  'FAQ faraidh': 'أسئلة شائعة في الفرائض',
  'Glosarium': 'المصطلحات',
  'Glosarium faraidh': 'مصطلحات الفرائض',
  'Rujukan faraidh': 'مراجع الفرائض',
  'Tanya jawab': 'سؤال وجواب',
  'Tanya jawab kasus waris': 'سؤال وجواب في مسائل الميراث',
  'Bantuan cepat': 'مساعدة سريعة',
  'Draf, menunggu pengecekan tim keilmuan.': 'مسودة، في انتظار مراجعة الفريق العلمي.',
  'Tautan disalin': 'تم نسخ الرابط',
  'Gagal menyalin. Salin dari bilah alamat.': 'تعذر النسخ. انسخ من شريط العنوان.',
  ' dan ': ' و',

  // ─── Beranda ───
  'Waris itu gampang, asal tahu urutannya.': 'الميراث سهل إذا عرفت ترتيبه.',
  'Hitung pembagian warisan menurut madzhab Syafi\'i, lengkap dengan alasan tiap angkanya, dan pelajari ilmunya pelan-pelan.': 'احسب قسمة التركة على مذهب الشافعي مع تعليل كل رقم، وتعلم العلم خطوة خطوة.',
  'Coba di ArifLab': 'جرب في ArifLab',
  'Isi data almarhum, ahli waris, dan harta. Sekitar 3 menit.': 'أدخل بيانات الميت والورثة والتركة. نحو ٣ دقائق.',
  'Mulai belajar': 'ابدأ التعلم',
  'Punyamu di perangkat ini': 'بياناتك على هذا الجهاز',
  'Kasus terakhir': 'آخر مسألة',
  'Lanjutkan kasus': 'أكمل المسألة',
  'Lanjutkan belajar': 'أكمل التعلم',
  'Lanjutkan latihan': 'أكمل التمارين',
  'Lanjut belajar': 'أكمل التعلم',
  'Mulai hitung': 'ابدأ الحساب',
  'Mulai latihan': 'ابدأ التمارين',
  'Belum ada kasus yang dihitung.': 'لم تحسب أي مسألة بعد.',
  'Belum ada kuis yang dikerjakan.': 'لم تحل أي اختبار بعد.',
  'Semua pelajaran sudah selesai.': 'أتممت جميع الدروس.',
  'Dari FAQ': 'من الأسئلة الشائعة',
  'Cari tahu': 'اكتشف',
  'Lihat materi': 'اعرض الدرس',
  'Tentang ARIF': 'عن ARIF',
  'Aplikasi Representasi Ilmu Faraidh': 'تطبيق تمثيل علم الفرائض',
  'singkatan dari': 'اختصار لـ',
  'menjaga ilmunya': 'المراجعة العلمية',
  'menulis kodenya': 'البرمجة',

  // ─── Awal hitung / riwayat ───
  'ArifLab': 'ArifLab',
  'Ruang buat nyoba simulasi hitung waris. Masukin kasusnya, ikutin langkahnya, tiap angka dijelasin lengkap sama alasannya.': 'مساحة لتجربة حساب المواريث: أدخل المسألة، واتبع الخطوات، وكل رقم مشروح بعلته.',
  'Skenario baru': 'مسألة جديدة',
  'Mulai baru': 'ابدأ من جديد',
  'Isi data almarhum, ahli waris, dan harta dari awal.': 'أدخل بيانات الميت والورثة والتركة من البداية.',
  ' Kasus sekarang tetap tersimpan di riwayat.': ' المسألة الحالية تبقى محفوظة في السجل.',
  'Lanjut kasus terakhir': 'أكمل آخر مسألة',
  'Impor file': 'استيراد ملف',
  'Buka file .json hasil ekspor dari aplikasi ini.': 'افتح ملف ‎.json‎ المصدر من هذا التطبيق.',
  'Mau belajar? Langsung kerjakan soal': 'تريد التعلم؟ حل تمرينا مباشرة',
  'Kasusnya sudah disiapkan. Kamu tinggal menebak pembagiannya, lalu pelajari cara menghitungnya langkah demi langkah.': 'المسألة جاهزة. خمن القسمة، ثم تعلم طريقة حسابها خطوة خطوة.',
  'Kerjakan': 'حل',
  'Lihat semua soal latihan': 'كل التمارين',
  'Riwayat hitung': 'سجل الحساب',
  'Riwayat hitung masih kosong': 'سجل الحساب فارغ',
  'Tiap kasus yang kamu mulai, dari skenario sendiri, latihan, atau materi, otomatis tersimpan di sini selama 30 hari.': 'كل مسألة تبدؤها، من إدخالك أو من التمارين أو الدروس، تحفظ هنا تلقائيا لمدة ٣٠ يوما.',
  'Tersimpan di perangkat ini selama 30 hari sejak terakhir dibuka.': 'محفوظة على هذا الجهاز ٣٠ يوما من آخر فتح.',
  'Tidak ada yang dibuka dua pekan terakhir.': 'لم يفتح شيء في الأسبوعين الأخيرين.',
  'Lihat semua riwayat': 'السجل كاملا',
  'Hapus semua riwayat': 'حذف السجل كله',
  'Tersimpan di riwayat': 'محفوظة في السجل',
  'Kasus yang sekarang sudah tersimpan di Riwayat hitung, jadi bisa kamu buka lagi kapan saja.': 'المسألة الحالية محفوظة في سجل الحساب، فيمكنك فتحها متى شئت.',
  'Isian yang sekarang tersimpan di Riwayat hitung sebagai data belum lengkap. Kamu bisa melanjutkannya kapan saja.': 'ما أدخلته محفوظ في سجل الحساب كبيانات غير مكتملة، ويمكنك إكماله متى شئت.',

  // ─── Wizard ───
  'Langkah isian': 'خطوات الإدخال',
  'Lima langkah saja': 'خمس خطوات فقط',
  'Ini peta langkahmu. Langkah yang sudah diisi bisa diklik untuk diubah.': 'هذه خريطة خطواتك. انقر على خطوة معبأة لتعديلها.',
  'Jawab pertanyaan besar ini. Tulisan abu-abu di bawahnya menjelaskan kenapa ditanya.': 'أجب عن هذا السؤال. النص الرمادي تحته يبين سبب السؤال.',
  'Kembali ke langkah sebelumnya, atau lanjut. Kalau masih ada yang kurang, alasannya tertulis di sini.': 'ارجع إلى الخطوة السابقة أو تابع. إن نقص شيء كتب سببه هنا.',
  'Maju dan mundur': 'التقدم والرجوع',
  'Almarhum': 'الميت',
  'Harta': 'التركة',
  'Kewajiban': 'الحقوق المتعلقة بالتركة',
  'Ahli waris': 'الورثة',
  'Kondisi khusus': 'أحوال خاصة',
  'Almarhum laki-laki atau perempuan?': 'الميت ذكر أم أنثى؟',
  'Ini menentukan pasangan yang ditanya nanti (istri atau suami) dan besar bagiannya.': 'بهذا يعرف الزوج أو الزوجة ومقدار نصيبه.',
  'Berapa harta peninggalannya?': 'كم التركة؟',
  'Semua yang dimiliki almarhum saat wafat: uang, tanah, kendaraan, emas, juga piutang yang bisa ditagih.': 'كل ما ملكه الميت عند موته: نقود وأرض ومركبات وذهب، والديون التي له على غيره.',
  'Ada kewajiban yang harus dibayar dulu?': 'هل هناك حقوق تقدم على القسمة؟',
  'Sebelum dibagi, harta dipakai dulu untuk mengurus jenazah, melunasi hutang, lalu menunaikan wasiat.': 'قبل القسمة يخرج من التركة مؤن التجهيز، ثم الديون، ثم الوصية.',
  'Siapa saja keluarga yang ditinggalkan?': 'من هم الأقارب الأحياء؟',
  'Masukkan semua kerabat yang masih hidup saat almarhum wafat. Nanti dihitung siapa yang dapat.': 'أدخل كل الأقارب الأحياء عند موت الميت، ثم يحسب من يرث.',
  'Ada kondisi khusus?': 'هل توجد أحوال خاصة؟',
  'Opsional. Kebanyakan kasus nggak butuh ini.': 'اختياري. أكثر المسائل لا تحتاجه.',
  'Nama almarhum': 'اسم الميت',
  'Bentar, masih ada yang perlu diisi': 'مهلا، بقي ما يجب إدخاله',
  'Masih ada yang kosong': 'بقيت خانات فارغة',
  'Lihat hasil': 'اعرض النتيجة',
  'Ringkasan kasus': 'ملخص المسألة',
  'Harta peninggalan': 'التركة',
  'Yang akan dibagi': 'ما يقسم',
  'Ganti jenis kelamin almarhum?': 'تغيير جنس الميت؟',
  'Mengganti jenis kelamin akan mengosongkan isian ahli waris dan kondisi khusus.': 'تغيير الجنس يفرغ خانات الورثة والأحوال الخاصة.',
  'Pasangan dan hubungan keluarga ikut berubah, jadi isian ahli waris dan kondisi khusus akan dikosongkan. Harta dan kewajiban tetap.': 'يتغير الزوج والقرابة، فتفرغ خانات الورثة والأحوال الخاصة. وتبقى التركة والحقوق.',
  'Ganti dan kosongkan': 'غير وأفرغ',

  // Harta
  'Total harta': 'مجموع التركة',
  'Total harta peninggalan': 'مجموع التركة',
  'Total langsung': 'المجموع مباشرة',
  'Rinci per jenis': 'مفصلا حسب النوع',
  'Tambah cepat': 'إضافة سريعة',
  'Cara mengisi harta': 'طريقة إدخال التركة',
  'Kosongkan': 'أفرغ',
  'Kosongkan total harta?': 'إفراغ مجموع التركة؟',
  'Rincian per jenis akan diganti dengan total baru ini.': 'سيستبدل التفصيل بهذا المجموع الجديد.',
  'Tabungan & kas': 'المدخرات والنقد',
  'Rekening bank, deposito, uang tunai': 'حسابات بنكية وودائع ونقد',
  'Tanah & bangunan': 'الأراضي والمباني',
  'Kendaraan': 'المركبات',
  'Emas & perhiasan': 'الذهب والحلي',
  'Emas batangan, perhiasan': 'سبائك ذهب وحلي',
  'Piutang': 'الديون التي للميت',
  'Uang almarhum yang dipinjam orang lain dan bisa ditagih': 'مال الميت عند غيره مما يمكن تحصيله',
  'Lainnya': 'غير ذلك',
  'Saham, barang berharga, usaha': 'أسهم وأشياء ثمينة وتجارة',
  'Untuk belajar, angka kira-kira boleh. Untuk pembagian nyata, pakai nilai taksiran saat harta dibagi.': 'للتعلم يكفي التقريب، وللقسمة الحقيقية استعمل القيمة وقت القسمة.',
  'Harta bersama suami-istri (gono-gini) diatur KHI, belum dihitung di sini. Masukkan bagian milik almarhum saja.': 'المال المشترك بين الزوجين تنظمه مدونة الأحكام الإندونيسية، ولا يحسب هنا. أدخل ملك الميت فقط.',
  'Transfer, tunai, atau barang yang dinilai dengan harga saat dibagi.': 'تحويل أو نقد أو أعيان تقوم بسعر وقت القسمة.',
  'Apa pun bentuknya.': 'أيا كان نوعه.',

  // Kewajiban
  'Pengurusan jenazah': 'مؤن التجهيز',
  'Biaya memandikan, mengafani, dan menguburkan almarhum. Ini didahulukan dari semuanya.': 'نفقة غسل الميت وتكفينه ودفنه، وهي مقدمة على كل شيء.',
  'Hutang': 'الديون',
  'Termasuk kewajiban yang tertunda, misalnya zakat yang belum dibayar, haji yang sudah dinazarkan, atau cicilan.': 'ومنها الحقوق المؤجلة كزكاة لم تؤد، أو حج منذور، أو أقساط.',
  'Termasuk hutang yang belum tercatat, misalnya zakat atau nazar.': 'ومنها ديون غير مكتوبة كالزكاة أو النذر.',
  'Wasiat': 'الوصية',
  'Maksimal 1/3 dari sisa harta setelah hutang. Kalau lebih, otomatis dipangkas.': 'أقصاها ثلث الباقي بعد الدين، وما زاد يرد تلقائيا.',
  'Maksimal 1/3 dari sisa harta setelah hutang.': 'أقصاها ثلث الباقي بعد الدين.',
  'Nggak ada? Biarkan kosong, dihitung Rp 0.': 'لا يوجد؟ اتركها فارغة، تحسب صفرا.',
  'Harta tidak langsung dibagi. Dipakai dulu untuk mengurus jenazah, lalu melunasi hutang, lalu menunaikan wasiat. Sisanya baru hak ahli waris.': 'لا تقسم التركة فورا: يخرج منها التجهيز، ثم الدين، ثم الوصية، والباقي حق الورثة.',
  'Dibayar dulu dari harta': 'يخرج أولا من التركة',
  'Mau ubah juga? Buka langkah Kewajiban.': 'تريد التعديل؟ افتح خطوة الحقوق.',

  // Ahli waris
  'Keluarga inti': 'الأسرة القريبة',
  'Kakek & nenek': 'الأجداد والجدات',
  'Cucu': 'الأحفاد',
  'Kakak/adik almarhum': 'إخوة الميت',
  'Paman & sepupu dari pihak ayah': 'الأعمام وأبناؤهم',
  'Keponakan': 'أبناء الإخوة',
  'kakek-nenek, cucu, kakak/adik, paman, keponakan': 'الأجداد، الأحفاد، الإخوة، الأعمام، أبناء الإخوة',
  'Suami': 'الزوج',
  'Istri': 'الزوجة',
  'Anak laki-laki': 'الابن',
  'Anak perempuan': 'البنت',
  'Ayah': 'الأب',
  'Ibu': 'الأم',
  'Cucu laki-laki': 'ابن الابن',
  'Cucu perempuan': 'بنت الابن',
  'Kakek (dari ayah)': 'الجد (أبو الأب)',
  'Nenek (dari ayah)': 'الجدة (أم الأب)',
  'Nenek (dari ibu)': 'الجدة (أم الأم)',
  'Kakak/adik laki-laki kandung': 'الأخ الشقيق',
  'Kakak/adik perempuan kandung': 'الأخت الشقيقة',
  'Kakak/adik laki-laki satu ayah': 'الأخ لأب',
  'Kakak/adik perempuan satu ayah': 'الأخت لأب',
  'Kakak/adik laki-laki satu ibu': 'الأخ لأم',
  'Kakak/adik perempuan satu ibu': 'الأخت لأم',
  'Keponakan laki-laki (kandung)': 'ابن الأخ الشقيق',
  'Keponakan laki-laki (satu ayah)': 'ابن الأخ لأب',
  'Paman (kandung)': 'العم الشقيق',
  'Paman (satu ayah)': 'العم لأب',
  'Sepupu laki-laki (kandung)': 'ابن العم الشقيق',
  'Sepupu laki-laki (satu ayah)': 'ابن العم لأب',
  'dari anak laki-laki': 'من الابن',
  'ayahnya ayah almarhum': 'أبو أبي الميت',
  'ibunya ayah almarhum': 'أم أبي الميت',
  'ibunya ibu almarhum': 'أم أم الميت',
  'ayahnya sama, ibunya beda': 'الأب واحد والأم مختلفة',
  'ibunya sama, ayahnya beda': 'الأم واحدة والأب مختلف',
  'anak dari kakak/adik laki-laki kandung': 'ابن الأخ الشقيق',
  'anak dari kakak/adik laki-laki satu ayah': 'ابن الأخ لأب',
  'saudara kandung ayah almarhum': 'أخو أبي الميت الشقيق',
  'saudara satu ayah dari ayah almarhum': 'أخو أبي الميت لأبيه',
  'anak laki-laki paman kandung': 'ابن العم الشقيق',
  'anak laki-laki paman satu ayah': 'ابن العم لأب',
  'Ubah jumlah': 'تعديل العدد',
  'Tetap terbuka karena sudah ada yang diisi': 'مفتوح لأن فيه بيانات',
  'Mereka termasuk dzawil arham: kerabat yang tidak punya bagian tertentu dan bukan penerima sisa. ': 'هم من ذوي الأرحام: أقارب ليسوا أصحاب فروض ولا عصبة. ',
  'Contohnya ayahnya ibu, anak dari anak perempuan, anak dari kakak/adik perempuan, paman dari pihak ibu, bibi, dan anak dari kakak/adik seibu. ': 'مثل أبي الأم، وأولاد البنت، وأولاد الأخت، والخال، والعمة والخالة، وأولاد الإخوة لأم. ',
  'Mereka baru mewarisi kalau tidak ada ahli waris di daftar ini, dan perhitungannya belum didukung aplikasi.': 'لا يرثون إلا عند عدم الورثة في هذه القائمة، وحسابهم غير مدعوم في التطبيق بعد.',

  // Kondisi khusus
  'Ada ahli waris yang wafat sebelum harta dibagi': 'مات أحد الورثة قبل القسمة',
  'Ini namanya munasakhat.': 'وهذه المناسخات.',
  'Urutin dari yang wafat duluan.': 'رتبهم من الأسبق موتا.',
  'Ada yang beda agama dengan almarhum': 'من يخالف الميت في الدين',
  'Beda agama menggugurkan hak waris.': 'اختلاف الدين يمنع الإرث.',
  'Ada yang terlibat dalam penyebab kematian almarhum': 'من تسبب في موت الميت',
  'Beda agama atau terlibat dalam penyebab kematian almarhum.': 'اختلاف الدين أو التسبب في موت الميت.',
  'Wafat sebelum dibagi': 'مات قبل القسمة',

  // ─── Layar hasil ───
  'Nah, ini pembagiannya': 'هذه هي القسمة',
  'Hitung kasus': 'حساب المسألة',
  'Angka di sini hasil hitung kasusmu. Mau latihan menebak pembagiannya dulu? Pindah ke mode Belajar.': 'الأرقام هنا نتيجة مسألتك. تريد التدرب على التخمين أولا؟ انتقل إلى وضع التعلم.',
  'Pindah ke mode Belajar?': 'الانتقال إلى وضع التعلم؟',
  'Jawaban akan disembunyikan dan kamu diminta menebak pembagiannya dulu. Data kasusmu tetap aman.': 'ستخفى الإجابة ويطلب منك تخمين القسمة أولا. بيانات مسألتك محفوظة.',
  'Tetap belajar': 'البقاء في التعلم',
  'Catatan. ': 'تنبيه. ',
  'Ubah data': 'تعديل البيانات',
  '← Ubah data': 'تعديل البيانات →',
  'Ubah harta': 'تعديل التركة',
  'Ubah harta peninggalan': 'تعديل التركة',
  'Ubah ahli waris': 'تعديل الورثة',
  'Harta yang dibagi': 'ما يقسم',
  'Pembagian': 'القسمة',
  'Hasil perhitungan': 'نتيجة الحساب',
  'Pohon keluarga': 'شجرة الأسرة',
  'Tabel faraidh': 'جدول المسألة',
  'Kanvas keluarga': 'لوحة الأسرة',
  'Tampilan kanvas': 'عرض اللوحة',
  'Keterangan pohon': 'مفتاح الشجرة',
  'Arti warna sorotan': 'معنى ألوان التظليل',
  'Warna menunjukkan kelompok, garis putus-putus berarti tidak dapat bagian. Klik siapa pun untuk penjelasannya.': 'اللون يدل على الفئة، والخط المتقطع يعني لا نصيب له. انقر على أي شخص لشرح حاله.',
  'Ketuk orang untuk melihat penjelasannya': 'انقر على شخص لشرح حاله',
  'Pasangan': 'الزوجان',
  'Keturunan': 'الفروع',
  'Orang tua & leluhur': 'الأصول',
  'Saudara & kerabat': 'الحواشي',
  'Terhalang': 'محجوب',
  'Terhalang (mahjub)': 'محجوب',
  'Kehalang (mahjub)': 'محجوب',
  'Tidak mewarisi': 'لا يرث',
  'Bukan ahli waris': 'ليس وارثا',
  'Bagian': 'النصيب',
  'Per orang': 'لكل واحد',
  'Nominal': 'المبلغ',
  'Pecahan': 'كسر',
  'Persen': 'نسبة مئوية',
  'Bentuk pecahan': 'صورة الكسر',
  'Disederhanakan': 'مبسط',
  'Penyebut sama': 'مقام موحد',
  'Cara tampil': 'طريقة العرض',
  'Atur tampilan': 'ضبط العرض',
  'Sembunyikan nominal': 'إخفاء المبالغ',
  'Tampilkan nominal': 'إظهار المبالغ',
  'disembunyikan': 'مخفي',
  'Tampilkan di samping nominal': 'اعرض بجانب المبلغ',
  'Bagian tiap orang. Ikon mata menyembunyikan nominal, ikon atur memilih pecahan atau persen.': 'نصيب كل واحد. أيقونة العين تخفي المبالغ، وأيقونة الضبط تختار الكسر أو النسبة.',
  'Bagian yang sama dalam persen, misal 1/6 ≈ 16,67%.': 'النصيب نفسه بالنسبة المئوية، مثل ١/٦ ≈ ١٦٫٦٧٪.',
  '12/72 · 26/72, gampang dibandingkan': '١٢/٧٢ · ٢٦/٧٢، سهل المقارنة',
  '1/6 · 13/36, paling ringkas': '١/٦ · ١٣/٣٦، أوجز',
  'bagian tertentu': 'فرض',
  'bagian tertentu + sisa': 'فرض وتعصيب',
  'Fardh (bagian tertentu)': 'الفرض',
  'Ashabah': 'العصبة',
  'Ashabah (sisa)': 'العصبة',
  'Sisa (ashabah)': 'العصبة',
  'Sisa': 'الباقي',
  'Sisa, 1 : 2': 'الباقي، للذكر مثل حظ الأنثيين',
  'sisa, dibagi bersama': 'الباقي، يقسم بينهم',
  'sama besar': 'بالسوية',
  'Untuk ahli waris': 'للورثة',
  'Dibagi ke ahli waris': 'يقسم على الورثة',
  'bukan untuk ahli waris': 'ليس للورثة',
  'seluruh harta yang dibagi': 'كل ما يقسم',
  'sudah habis dibagi': 'استغرقت القسمة',
  'Asal masalah': 'أصل المسألة',
  'Tashih': 'التصحيح',
  '\'Aul': 'العول',
  'Radd (dengan suami/istri)': 'الرد مع أحد الزوجين',
  'Jami\'ah': 'الجامعة',
  'Saham jami\'ah': 'سهام الجامعة',
  'Penyebutnya:': 'المخارج:',
  'Penyebut bagian yang ada.': 'مخارج الفروض الموجودة.',
  'Asal masalah dinaikkan supaya semua bagian muat.': 'يرفع أصل المسألة حتى تتسع الفروض.',
  'Jumlah bagian tertentu melebihi harta, jadi semua bagian dikurangi secara seimbang.': 'زادت الفروض على المال، فتنقص كلها بنسبة واحدة.',
  'Semua bagian sudah pas, tidak ada sisa.': 'الفروض مساوية للأصل، ولا باقي.',
  'yang besar habis dibagi yang kecil': 'الأكبر يقبل القسمة على الأصغر',
  'punya faktor persekutuan': 'بينهما عامل مشترك',
  'tidak punya faktor persekutuan': 'لا عامل مشترك بينهما',
  'Jenis kasus': 'نوع المسألة',
  'Tentang kasus ini': 'عن هذه المسألة',
  'kasus ini': 'هذه المسألة',
  'Bagiannya di kasus ini': 'نصيبه في هذه المسألة',
  'Ahli waris lain yang terdampak': 'ورثة آخرون تأثروا',
  'Akibatnya:': 'فأثره:',
  'Kapan dapat berapa?': 'متى يأخذ كم؟',
  'Mode belajar: bagian orang ini masih disembunyikan. Lihat "Kapan dapat berapa?", lalu tebak kondisi mana yang cocok.': 'وضع التعلم: نصيب هذا الشخص مخفي. اقرأ «متى يأخذ كم؟» ثم خمن الحال المناسبة.',
  'Perlu diperhatikan': 'ينبغي الانتباه',
  'Perlu keputusanmu': 'يحتاج قرارك',
  'Bulatkan bagian tiap orang ke': 'قرب نصيب كل واحد إلى',
  'Muncul hanya kalau ada angka yang tidak bulat. Pilih sesuai cara membagi: transfer atau tunai.': 'يظهر فقط إذا كانت الأرقام غير صحيحة. اختر حسب طريقة القسمة: تحويل أو نقد.',
  'Pas sampai rupiah terakhir. Cocok kalau dibagi lewat transfer bank.': 'دقيق إلى آخر روبية. مناسب للتحويل البنكي.',
  'Hampir pas, angka lebih rapi.': 'قريب جدا، والأرقام أرتب.',
  'Paling praktis kalau dibagi tunai.': 'الأيسر عند القسمة نقدا.',
  'dibulatkan ke bawah': 'مقرب إلى الأدنى',
  'Setelah dibulatkan ke bawah, tersisa': 'بعد التقريب إلى الأدنى يبقى',
  'Sepakati sisa pembulatan dan cara membagi.': 'اتفقوا على فرق التقريب وطريقة القسمة.',

  // Langkah perhitungan
  'Pelajari langkah perhitungan': 'تعلم خطوات الحساب',
  'Pelajari langkahnya': 'تعلم الخطوات',
  'Buka ini untuk melihat cara hitungnya, satu langkah sekali. Pohon dan tabel ikut menyorot yang sedang dibahas.': 'افتح هذا لترى طريقة الحساب خطوة خطوة، وتظلل الشجرة والجدول ما يشرح.',
  'Langkah demi langkah': 'خطوة خطوة',
  'Tampilkan semua': 'اعرض الكل',
  'Daftar langkah': 'قائمة الخطوات',
  'Langkah': 'الخطوة',
  'belum dibahas': 'لم يشرح بعد',
  'Cara menghitungnya': 'طريقة الحساب',
  'Pembahasan langkah demi langkah': 'الشرح خطوة خطوة',
  'Pembahasan soal': 'حل التمرين',
  'Mode fokus': 'وضع التركيز',
  'Tutup mode fokus': 'إغلاق وضع التركيز',
  'Layar penuh': 'ملء الشاشة',
  'Mode fokus tidak tersedia di mobile': 'وضع التركيز غير متاح في الهاتف',
  'Gunakan desktop untuk membuka mode fokus.': 'استعمل الحاسوب لفتح وضع التركيز.',
  'Putar animasi': 'تشغيل الحركة',
  'Jeda animasi': 'إيقاف الحركة',
  'Nyalakan animasi': 'تفعيل الحركة',
  'Matikan animasi': 'تعطيل الحركة',
  'Satu pertanyaan sekali': 'سؤال واحد في كل مرة',
  'Semua pertanyaan': 'كل الأسئلة',
  'Kamu sudah mengikuti seluruh pembagian, langkah demi langkah. Tabelnya sekarang lengkap.': 'تابعت القسمة كلها خطوة خطوة، واكتمل الجدول الآن.',
  '· geser ke samping kalau terpotong': '· اسحب جانبا إن كان مقطوعا',

  // Mode belajar / tebak
  'Tebak pembagian akhirnya': 'خمن القسمة النهائية',
  'Jawabanmu': 'إجابتك',
  'Jawabanmu belum tepat': 'إجابتك غير صحيحة',
  'Benar semua!': 'كلها صحيحة!',
  'Pembagianmu sama persis dengan hasil perhitungan. Cocokkan caranya di langkah perhitungan.': 'قسمتك مطابقة للنتيجة. قارن طريقتك بخطوات الحساب.',
  'Tulis bagian akhir tiap orang dari': 'اكتب النصيب النهائي لكل واحد من',
  '. Yang tidak mendapat bagian, isi': '. ومن لا نصيب له فاكتب',
  'Kerjakan di kartu Jawabanmu. Langkah perhitungan dan angka di tabel terbuka setelah jawabanmu benar atau kamu membuka jawaban.': 'حل في بطاقة إجابتك. تفتح الخطوات وأرقام الجدول بعد صحة إجابتك أو فتح الحل.',
  'Langkah perhitungan terbuka setelah jawabanmu di kartu': 'تفتح خطوات الحساب بعد إجابتك في البطاقة',
  'Cocokkan jawabanmu, lalu pelajari cara menghitungnya langkah demi langkah.': 'قارن إجابتك، ثم تعلم الحساب خطوة خطوة.',
  'Jawab soalnya dulu': 'أجب عن التمرين أولا',
  'Coba dulu': 'جرب أولا',
  'Kamu belum nyoba jawab sama sekali. Sekali coba dulu, yuk.': 'لم تجرب الإجابة بعد. جرب مرة واحدة.',
  'Lihat jawaban': 'اعرض الحل',
  'Kunci jawaban': 'مفتاح الحل',
  'Semua jawaban langsung kebuka, kamu nggak bisa nebak kasus ini lagi.': 'ستفتح كل الإجابات، ولن تستطيع تخمين هذه المسألة مرة أخرى.',
  'Tahan untuk buka': 'اضغط مطولا للفتح',
  'Tahan untuk pindah': 'اضغط مطولا للانتقال',
  'Langsung lihat hasil.': 'اعرض النتيجة مباشرة.',
  'Tentukan bagian tiap ahli waris': 'حدد نصيب كل وارث',
  'untuk melanjutkan': 'للمتابعة',

  // Kartu lain / langkah selanjutnya
  'Habis ini ngapain?': 'ماذا بعد؟',
  'Daftar hal yang biasanya dilakukan keluarga setelah tahu pembagiannya.': 'أمور تفعلها الأسرة عادة بعد معرفة القسمة.',
  'Pastikan biaya jenazah dan hutang sudah beres.': 'تأكدوا من سداد مؤن التجهيز والديون.',
  'Tunaikan wasiat.': 'نفذوا الوصية.',
  'Musyawarahkan hasil ini dengan semua ahli waris.': 'تشاوروا في هذه النتيجة مع جميع الورثة.',
  'Urus dokumen yang dibutuhkan.': 'أنجزوا الوثائق اللازمة.',
  'Misalnya surat keterangan ahli waris untuk balik nama atau pencairan rekening.': 'مثل وثيقة حصر الورثة لنقل الملكية أو صرف الحسابات.',
  'Kalau ragu atau ada perselisihan, tanya ahlinya.': 'عند الشك أو الخلاف، اسألوا أهل العلم.',
  'Ustadz yang paham faraidh atau lembaga yang berwenang.': 'عالما بالفرائض أو جهة مختصة.',
  'Bagikan file kasus atau tunjukkan layar ini supaya semua melihat angka yang sama.': 'شارك ملف المسألة أو اعرض هذه الشاشة ليرى الجميع الأرقام نفسها.',
  'Ekspor': 'تصدير',
  'Ekspor ke': 'تصدير إلى',
  'Laporan lengkap dengan langkah hitung.': 'تقرير كامل مع خطوات الحساب.',
  'Bisa dibuka lagi di aplikasi ini lewat Impor.': 'يمكن فتحه مرة أخرى في هذا التطبيق عبر الاستيراد.',
  'Gambar pembagian.': 'صورة القسمة.',
  'Salin data kasus': 'نسخ بيانات المسألة',
  'Kasus ini belum bisa dihitung di sini': 'لا يمكن حساب هذه المسألة هنا بعد',
  'Waduh, ada yang nggak beres di mesin hitungnya': 'عذرا، حدث خلل في محرك الحساب',
  'Ini bukan salah isianmu. Tolong laporkan dan lampirkan data kasus di bawah.': 'ليس الخطأ في إدخالك. أبلغنا وأرفق بيانات المسألة أدناه.',

  // Kapan dapat berapa (ringkasan syarat bagian)
  'Almarhum punya anak atau cucu dari anak laki-laki.': 'للميت فرع وارث.',
  'Almarhum tidak punya anak atau cucu dari anak laki-laki.': 'ليس للميت فرع وارث.',
  'Almarhumah punya anak atau cucu dari anak laki-laki.': 'للميتة فرع وارث.',
  'Almarhumah tidak punya anak atau cucu dari anak laki-laki.': 'ليس للميتة فرع وارث.',
  'Ada anak/cucu, atau ada dua saudara atau lebih.': 'وجود الفرع الوارث أو جمع من الإخوة.',
  'Tidak ada anak/cucu dan saudaranya kurang dari dua.': 'عدم الفرع الوارث وعدم الجمع من الإخوة.',
  'Hanya bersama ayah dan suami/istri (umariyyatain).': 'مع الأب وأحد الزوجين فقط (العمريتان).',
  'Ada anak laki-laki atau cucu laki-laki.': 'وجود الفرع الوارث الذكر.',
  'Hanya ada anak/cucu perempuan.': 'وجود الفرع الوارث الأنثى فقط.',
  'Tidak ada anak maupun cucu.': 'عدم الفرع الوارث.',
  'Ada anak laki-laki, cucu laki-laki, atau ayah.': 'وجود الابن أو ابن الابن أو الأب.',
  'Tidak ada anak laki-laki, cucu laki-laki, maupun ayah.': 'عدم الابن وابن الابن والأب.',
  'Sendirian, tanpa anak laki-laki.': 'منفردة، بلا معصب.',
  'Dua orang atau lebih, tanpa anak laki-laki.': 'اثنتان فأكثر، بلا معصب.',
  'Bersama anak laki-laki (ashabah bil ghair).': 'مع الابن (عصبة بالغير).',
  'Selalu mewarisi dan tidak pernah terhalang. Bersama anak perempuan: dapat dua kali bagiannya.': 'يرث دائما ولا يحجب حرمانا. ومع البنت: له مثل حظ الأنثيين.',

  // ─── Teks bersisipan & label satu kata ───
  'Mode fokus: {judul}': 'وضع التركيز: {judul}',
  'ambil salah satu': 'يؤخذ أحدهما',
  '{besar} ÷ {kecil} = {hasil}, habis': '{besar} ÷ {kecil} = {hasil}، بلا باق',
  'ambil yang besar': 'يؤخذ الأكبر',
  'FPB {fpb}': 'القاسم المشترك {fpb}',
  'FPB 1': 'القاسم المشترك ١',
  'Radd': 'الرد',
  'Putar': 'تشغيل',
  'Jeda': 'إيقاف',
  'Langkah {nomor} dari {total}': 'الخطوة {nomor} من {total}',
  'semua kemungkinan bagian {nama}': 'كل أحوال {nama}',
  'Ubah jumlah {label}': 'تعديل عدد {label}',
  '{nama} (tidak diisi)': '{nama} (غير معبأ)',
  ' + sisa': ' + الباقي',
  '{nama}. Lihat penjelasan': '{nama}. اعرض الشرح',
  'mengurangi {dari} → {menjadi}': 'ينقص من {dari} إلى {menjadi}',
  '{ashl} × {fardh} = {porsi}, + sisa {sisa}': '{ashl} × {fardh} = {porsi}، + الباقي {sisa}',
  'Bagian tertentu {fardh}': 'فرضه {fardh}',
  ' · dari {nama}': ' · من {nama}',
  ' (sudah wafat)': ' (ميت)',
  'Terhalang oleh {oleh}.': 'محجوب بـ{oleh}.',
  'Tidak mewarisi karena {alasan}.': 'لا يرث بسبب {alasan}.',
  'Pembulatan': 'التقريب',
  'File-nya nggak bisa dibuka: {pesan}': 'تعذر فتح الملف: {pesan}',
  'Kuis terakhir: {judul}, skor {skor}': 'آخر اختبار: {judul}، النتيجة {skor}',
  'Soal': 'التمرين',
  'Pembahasan': 'الحل',
  '{label} dari siapa?': '{label} من أي أصل؟',
  'Beri nama {label} (opsional)': 'سم {label} (اختياري)',
  'Kurangi {label}': 'أنقص {label}',
  'Tambah {label}': 'زد {label}',
  'Nama {label}': 'اسم {label}',
  'Nama, misal {contoh}': 'الاسم، مثل {contoh}',
  'Kerabat': 'قريب',
  ', sudah wafat': '، ميت',
  '{label} (sudah wafat)': '{label} (ميت)',
  '{orang} (ahli waris {mayit})': '{orang} (وارث {mayit})',
  'Naikkan {label}': 'قدم {label}',
  'Turunkan {label}': 'أخر {label}',
  'Buka': 'افتح',
  'Lanjut': 'تابع',
  'Hapus {judul}': 'احذف {judul}',
  'Tentang {label}': 'عن {label}',
  'Maks. {batas} (1/3 dari sisa setelah hutang).': 'الحد {batas} (ثلث الباقي بعد الدين).',
  'Laki-laki': 'ذكر',
  'Perempuan': 'أنثى',
  'Soal latihan {kode}': 'تمرين {kode}',
  'Tutup {label}': 'أغلق {label}',
  'dan': 'و',
  'Ashl masalah': 'أصل المسألة',
  'Berikutnya: {judul}': 'التالي: {judul}',
  '{selesai}/{total} pelajaran': '{selesai}/{total} دروس',
  '{selesai}/{total} soal hitung': '{selesai}/{total} تمارين',
  'Wasiat dipangkas ke batas 1/3. Kelebihan {lebih} hanya berlaku bila semua ahli waris setuju.': 'ردت الوصية إلى الثلث، والزائد {lebih} موقوف على إجازة جميع الورثة.',
  'Aman, masih di bawah batas 1/3 (maks. {batas}).': 'لا بأس، دون الثلث (الحد {batas}).',
  'Dari penyebut {daftar}, yang': 'من المخارج {daftar}، وهي',
  'Bagian sekelompok ahli waris belum habis dibagi jumlah orangnya': 'سهام فريق من الورثة لا تنقسم على عدد رؤوسهم',
  ', jadi semua dikali {kali}.': '، فتضرب المسألة كلها في {kali}.',
  'munasakhat': 'المناسخات',
  'Angka sudah ada. Ini urutan yang biasanya dilakukan keluarga. (Draf, menunggu pengecekan tim keilmuan.)': 'الأرقام جاهزة. هذا ما تفعله الأسرة عادة. (مسودة، في انتظار مراجعة الفريق العلمي.)',
  'Animasi': 'الحركة',
  'benar, atau setelah kamu membuka jawabannya. Coba hitung sendiri dulu, lalu cocokkan caranya di sini.': 'صحيحة، أو بعد فتح الحل. جرب الحساب بنفسك أولا، ثم قارن طريقتك هنا.',
  'tidak dapat bagian.': 'لا نصيب له.',
  'Ada angka yang nggak bulat · dibulatkan ke {satuan}': 'أرقام غير صحيحة · تقرب إلى {satuan}',
  'Misalnya bagian {nama} susah dibagi tunai. Buka untuk memilih pembulatan dan melihat sisanya.': 'مثل نصيب {nama} يصعب دفعه نقدا. افتح لاختيار التقريب ورؤية الباقي.',
  'yang belum terbagi. Sisa ini tidak dibagi diam-diam; sepakati bersama para ahli waris.': 'لم يقسم. لا يقسم هذا الباقي خفية؛ اتفقوا عليه مع الورثة.',
  'atau': 'أو',
  'Isi dulu: {nama}.': 'أدخل أولا: {nama}.',
  '{benar} dari {total} orang sudah benar. Perbaiki: {nama}.': '{benar} من {total} صحيحة. صحح: {nama}.',
  'Harta dibagi menjadi {penyebut} bagian yang sama; {nama} mendapat {saham} bagian.': 'تقسم التركة {penyebut} سهما متساوية؛ ولـ{nama} {saham} سهما.',
  'Biaya jenazah, hutang, dan wasiat tidak ikut berubah.': 'مؤن التجهيز والدين والوصية لا تتغير.',
  'Hasil langsung dihitung ulang. Untuk kerabat lain, buka langkah Ahli waris (ikon pensil di atas pohon).': 'تعاد النتيجة فورا. ولأقارب آخرين افتح خطوة الورثة (أيقونة القلم فوق الشجرة).',
  ': tempat ilmu waris Islam dipelajari lewat penjelasan, latihan, dan': ': مكان لتعلم علم المواريث بالشرح والتمارين و',
  ', ruang untuk mencoba simulasi hitung waris sendiri.': '، مساحة لتجربة حساب المواريث بنفسك.',
  'Aplikasi ini berawal dari tugas akhir beberapa mahasiswa Hukum Keluarga Islam di': 'بدأ هذا التطبيق مشروع تخرج لطلاب الأحوال الشخصية في',
  'Kami ingin ilmu faraidh terasa dekat: bisa dihitung, sekaligus dipahami alasannya.': 'أردنا أن يكون علم الفرائض قريبا: يحسب وتفهم علله.',
  ', dan ': '، و',
  ', ': '، ',
  'Semuanya berjalan di bawah bimbingan': 'وكل ذلك بإشراف',
  'Nemu yang janggal?': 'وجدت شيئا غريبا؟',
  ' skenario': ' المسألة',
  'Garis putus = tidak mewarisi': 'خط متقطع = لا يرث',
  'Mendatar = menikah, turun = anak': 'أفقي = زواج، نازل = ولد',
  'Kerabat lain': 'أقارب آخرون',
  'dari {nama}': 'من {nama}',
  '{nomor}. Ahli waris {label}': '{nomor}. ورثة {label}',
  'dibuka {waktu}': 'فتح {waktu}',
  'Lihat semua riwayat ({jumlah})': 'السجل كاملا ({jumlah})',
  'Hapus semua riwayat?': 'حذف السجل كله؟',
  'Hapus kasus ini?': 'حذف هذه المسألة؟',
  '{jumlah} kasus': '{jumlah} مسائل',
  'akan dihapus dari perangkat ini dan tidak bisa dikembalikan.': 'ستحذف من هذا الجهاز ولا يمكن استرجاعها.',
  'Total {jumlah} akan dihapus dan perlu diisi ulang.': 'سيحذف المجموع {jumlah} ويلزم إدخاله من جديد.',
  'Berurutan dari atas.': 'بالترتيب من الأعلى.',
  'Wasiat dipangkas jadi {dipakai} (batas 1/3). Kelebihan {lebih} hanya berlaku kalau semua ahli waris setuju.': 'ردت الوصية إلى {dipakai} (الثلث). والزائد {lebih} موقوف على إجازة جميع الورثة.',
  '(boleh dikosongkan)': '(يجوز تركه فارغا)',
  'Lewati': 'تخط',
  "Hasil ini menurut madzhab Syafi'i. Untuk pembagian nyata, musyawarahkan dengan ahli faraidh atau ustadz setempat.": 'هذه النتيجة على مذهب الشافعي. وللقسمة الحقيقية شاوروا أهل الفرائض أو عالما محليا.',
  "Mas'alah gabungan untuk semua mayit": 'المسألة الجامعة لجميع الأموات',
  ", sesudah 'aul atau radd bila ada. Bukan bagian fardh awalnya.": '، بعد العول أو الرد إن وجد، لا الفرض الأصلي.',
  "{saham} dari {jamiah} saham jami'ah": '{saham} من {jamiah} سهام الجامعة',
  'Skenario pribadi': 'مسألة خاصة',
  'Contoh materi': 'مثال من درس',
  'Belum ada ahli waris': 'لا ورثة بعد',
  'Data belum lengkap': 'بيانات غير مكتملة',
  ' · ada yang wafat sebelum pembagian': ' · مات بعضهم قبل القسمة',
  'baru saja': 'الآن',
  'dasar': 'مبتدئ',
  'menengah': 'متوسط',
  'sulit': 'متقدم',
  'Cucu laki-laki (dari anak lk)': 'ابن الابن',
  'Cucu perempuan (dari anak lk)': 'بنت الابن',
  'Kakek (ayahnya ayah)': 'الجد (أبو الأب)',
  'Nenek (ibunya ayah)': 'الجدة (أم الأب)',
  'Nenek (ibunya ibu)': 'الجدة (أم الأم)',
  'Saudara lk kandung': 'الأخ الشقيق',
  'Saudari kandung': 'الأخت الشقيقة',
  'Saudara lk sebapak': 'الأخ لأب',
  'Saudari sebapak': 'الأخت لأب',
  'Saudara lk seibu': 'الأخ لأم',
  'Saudari seibu': 'الأخت لأم',
  'Keponakan lk (dari saudara kandung)': 'ابن الأخ الشقيق',
  'Keponakan lk (dari saudara sebapak)': 'ابن الأخ لأب',
  'Paman kandung (saudara ayah)': 'العم الشقيق',
  'Paman sebapak': 'العم لأب',
  'Sepupu lk (dari paman kandung)': 'ابن العم الشقيق',
  'Sepupu lk (dari paman sebapak)': 'ابن العم لأب',
  "Normal ('adilah)": 'عادلة',
  'Jumlah bagian tertentu (fardh) tidak melebihi harta; bila ada sisa, diambil ashabah.': 'الفروض لا تزيد على المال؛ وإن بقي شيء فللعصبة.',
  'Ada sisa tanpa ashabah; sisa dikembalikan ke pemilik bagian tertentu.': 'بقي شيء ولا عاصب؛ فيرد على أصحاب الفروض.',
  'Ada sisa tanpa ashabah; sisa dikembalikan ke pemilik bagian tertentu selain suami/istri.': 'بقي شيء ولا عاصب؛ فيرد على أصحاب الفروض غير الزوجين.',
  'Kenapa tidak dapat?': 'لماذا لا يرث؟',
  'Kenapa segitu?': 'لماذا هذا النصيب؟',
  'Sisa untuk dzawil arham': 'الباقي لذوي الأرحام',
  'Suami/istri tidak menerima sisa': 'لا يرد على الزوجين',
  'Sisa: dzawil arham / baitul mal': 'الباقي: لذوي الأرحام أو بيت المال',
  'Untuk dzawil arham bila ada; bila tidak, ke baitul mal': 'لذوي الأرحام إن وجدوا؛ وإلا فلبيت المال',
  'terlibat dalam penyebab kematian almarhum': 'التسبب في موت الميت',
  'berbeda agama dengan almarhum': 'اختلاف الدين مع الميت',
  'berstatus budak': 'الرق',
  'urutan wafatnya tidak diketahui': 'الجهل بترتيب الموت',
  'akan menimbulkan hitungan berputar (daur)': 'لأنه يؤدي إلى الدور',
  'Kok kakek dari ibu, cucu dari anak perempuan, atau bibi tidak ada?': 'لماذا لا يوجد أبو الأم وأولاد البنت والعمة؟',
  'Yakin mau lihat jawaban?': 'هل تريد رؤية الحل؟',
  'Pindah ke Hitung kasus?': 'الانتقال إلى حساب المسألة؟',
  'Mulai kasus baru?': 'بدء مسألة جديدة؟',
  'Lanjut: {nama}': 'التالي: {nama}',
  'Hasil': 'النتيجة',
  'Pilih dulu jenis kelamin almarhum.': 'اختر جنس الميت أولا.',
  'Isi total harta peninggalan dulu, harus lebih dari Rp 0.': 'أدخل مجموع التركة أولا، ويجب أن يزيد على الصفر.',
  'Tambahkan minimal satu ahli waris.': 'أضف وارثا واحدا على الأقل.',
};
